### PR TITLE
Homework M10-L26 Selenium: CI

### PR DESCRIPTION
**Pull request by shield75**

### CODE REVIEW

**Comment by khanhtestpro** [comment]
//Comment from HW team,
Hello,
Your homework has been reviewed.
Great job on creating your Homework 26 and use Jenkins Test Job but you Regression suites in Jenkins please add it. Can you please take a photo of the Test result for me? 

https://share.zight.com/jkujdpgq

Best wishes from the HW team (Khanh, khanh@testpro.io)

**Comment by shield75** [comment]
> //Comment from HW team, Hello, Your homework has been reviewed. Great job on creating your Homework 26 and use Jenkins Test Job but you Regression suites in Jenkins please add it. Can you please take a photo of the Test result for me?
> 
> https://share.zight.com/jkujdpgq
> 
> Best wishes from the HW team (Khanh, [khanh@testpro.io](mailto:khanh@testpro.io))

Screenshot (525)
Screenshot (527)
Screenshot (526)

I have also added the regression.xml file.

**Comment by shield75** [comment]
> //Comment from HW team, Hello, Your homework has been reviewed. Great job on creating your Homework 26 and use Jenkins Test Job but you Regression suites in Jenkins please add it. Can you please take a photo of the Test result for me?
> 
> https://share.zight.com/jkujdpgq
> 
> Best wishes from the HW team (Khanh, [khanh@testpro.io](mailto:khanh@testpro.io))

Screenshot (529)
Regression suite

**Comment by khanhtestpro** [comment]
//Comment from HW team,
Hello,
Your homework has been reviewed.
Great job on creating your Homework 26 and use Smoke and Regression suites in Jenkins.


Best wishes from the HW team (Khanh, khanh@testpro.io)"

> > //Comment from HW team, Hello, Your homework has been reviewed. Great job on creating your Homework 26 and use Jenkins Test Job but you Regression suites in Jenkins please add it. Can you please take a photo of the Test result for me?
> > https://share.zight.com/jkujdpgq
> > Best wishes from the HW team (Khanh, [khanh@testpro.io](mailto:khanh@testpro.io))
> 
> Screenshot (525) Screenshot (527) Screenshot (526)
> 
> I have also added the regression.xml file.

**Pull request merged**
