### PR TITLE
Homework #20: Selenium Waits

### PR DESCRIPTION
**Pull request by shield75**

### CODE REVIEW

**Comment by khanhtestpro** [comment]
//Comment from HW team,
Hello,
Your homework has been reviewed.
HW 20 is empty please check

https://share.zight.com/2NuoDj9E

Best wishes from the HW team (Khanh, khanh@testpro.io)

**Comment by shield75** [comment]
> //Comment from HW team, Hello, Your homework has been reviewed. HW 20 is empty please check
> 
> https://share.zight.com/2NuoDj9E
> 
> Best wishes from the HW team (Khanh, [khanh@testpro.io](mailto:khanh@testpro.io))

Can you please check again. Thanks

**Comment by khanhtestpro** [comment]
//Comment from HW team,
Hello,
Your homework has been reviewed.
You haven't add Homework 20 in TestNG so can't run the script. Please check
https://share.zight.com/Z4u98kQ4

Best wishes from the HW team (Khanh, khanh@testpro.io)"

**Comment by shield75** [comment]
> //Comment from HW team, Hello, Your homework has been reviewed. You haven't add Homework 20 in TestNG so can't run the script. Please check https://share.zight.com/Z4u98kQ4
> 
> Best wishes from the HW team (Khanh, [khanh@testpro.io](mailto:khanh@testpro.io))"

Extremely sorry for the fault. I have updated my TestNG file. Can you please check now?

**Comment by khanhtestpro** [comment]
//Comment from HW team,
Hello,
Your homework has been reviewed.
Great job on creating your Homework 20 and implementing Explicit waits

https://share.zight.com/yAueE76m

Best wishes from the HW team (Khanh, khanh@testpro.io)

**Pull request merged**
